#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_NAME_LENGTH 50
#define EMPTY_STR ""

// Action messages
#define PERMIT_MESSAGE "PERMIT"
#define DENY_MESSAGE "DENY"

// Action types
#define REQUEST_STR "REQUEST"
#define READ_STR "READ"
#define INSERT_STR "INSERT"
#define MODIFY_STR "MODIFY"
#define DELETE_STR "DELETE"
#define EXECUTE_STR "EXECUTE"

// Operation abbreviations
#define READ_ABBV "R"
#define INSERT_ABBV "I"
#define MODIFY_ABBV "M"
#define DELETE_ABBV "D"
#define EXECUTE_ABBV "X"

// Server response status codes
#define USER_NOT_FOUND_STATUS "USER_NOT_FOUND"
#define REQUEST_DENIED_STATUS "REQUEST_DENIED"
#define PERMISSION_DENIED_STATUS "PERMISSION_DENIED"
#define TOKEN_EXPIRED_STATUS "TOKEN_EXPIRED"
#define RESOURCE_NOT_FOUND_STATUS "RESOURCE_NOT_FOUND"
#define OPERATION_NOT_PERMITTED_STATUS "OPERATION_NOT_PERMITTED"
#define PERMISSION_GRANTED_STATUS "PERMISSION_GRANTED"

#define SIGNED_TOKEN_STATUS "SIGNED"

#endif // CONSTANTS_H
