/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"


void
authorization_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * auth_1_arg;
	acces_token_struct  *result_2;
	access_token_req  access_1_arg;
	char * *result_3;
	action_req  validate_action_1_arg;
	auth_token_struct  *result_4;
	auth_token_struct  approve_req_token_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AUTHORIZATION, OAUTH, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = auth_1(&auth_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = access_1(&access_1_arg, clnt);
	if (result_2 == (acces_token_struct *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = validate_action_1(&validate_action_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = approve_req_token_1(&approve_req_token_1_arg, clnt);
	if (result_4 == (auth_token_struct *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	authorization_1 (host);
exit (0);
}
